# -*- coding: utf-8 -*-
"""nfl_visual_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6VITdISfz0-2priBm8F9FNkQLRWQ2rV
"""

import pandas as pd
import json
from google.colab import files

XL = 'nfl_draft_analysis.xlsx'
xl = pd.ExcelFile(XL)

anova = xl.parse('ANOVA_significance')

avg_data = {}
for sheet in xl.sheet_names:
    if sheet.startswith('AVG_'):
        pos = sheet[4:]
        df = xl.parse(sheet)
        stat_cols = [c.replace('_mean', '') for c in df.columns if c.endswith('_mean')]
        rows = []
        for _, row in df.iterrows():
            r = {'slot': str(row.get('draft_slot_label', '')), 'n': int(row.get('n_players', 0))}
            for s in stat_cols:
                for m in ['mean', 'median', 'std']:
                    k = f'{s}_{m}'
                    if k in row:
                        r[k] = round(float(row[k]), 2)
            rows.append(r)
        avg_data[pos] = {'stats': stat_cols, 'rows': rows}

anova_json = anova.to_json(orient='records')
avg_json   = json.dumps(avg_data)

sig_count = int((anova['significant'] == 'YES').sum())
total     = len(anova)
positions = sorted(anova['position'].unique().tolist())

#HTML
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NFL Draft Dashboard</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: system-ui, sans-serif; background: #f8f8f8; color: #222; }}

  header {{ background: #1a1a2e; color: #fff; padding: 16px 24px; display: flex; align-items: center; gap: 12px; }}
  header h1 {{ font-size: 16px; font-weight: 600; }}
  header small {{ font-size: 11px; opacity: .6; }}

  .tabs {{ display: flex; background: #fff; border-bottom: 1px solid #e5e5e5; padding: 0 24px; }}
  .tab-btn {{ padding: 12px 18px; font-size: 13px; border: none; background: none; cursor: pointer;
              border-bottom: 2px solid transparent; color: #666; font-family: inherit; }}
  .tab-btn.active {{ color: #1a1a2e; border-bottom-color: #1a1a2e; font-weight: 600; }}

  .page {{ display: none; padding: 20px 24px; max-width: 1100px; margin: 0 auto; }}
  .page.active {{ display: block; }}

  .stats-row {{ display: flex; gap: 12px; margin-bottom: 20px; flex-wrap: wrap; }}
  .stat-box {{ background: #fff; border: 1px solid #e5e5e5; border-radius: 8px;
               padding: 14px 18px; min-width: 120px; flex: 1; }}
  .stat-box .val {{ font-size: 28px; font-weight: 700; }}
  .stat-box .lbl {{ font-size: 11px; color: #888; margin-top: 2px; }}
  .green {{ color: #2d7a2d; }}
  .gray  {{ color: #aaa; }}

  .toolbar {{ display: flex; gap: 12px; align-items: center; margin-bottom: 16px; flex-wrap: wrap; }}
  .toolbar label {{ font-size: 12px; color: #666; }}
  .toolbar select {{ font-size: 12px; padding: 5px 8px; border: 1px solid #ddd;
                     border-radius: 5px; background: #fff; font-family: inherit; }}

  .card {{ background: #fff; border: 1px solid #e5e5e5; border-radius: 8px;
           padding: 16px; margin-bottom: 16px; }}

  .chart-wrap {{ position: relative; width: 100%; }}

  table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
  th {{ text-align: left; padding: 7px 10px; background: #f4f4f4;
        border-bottom: 1px solid #e5e5e5; font-weight: 600; color: #555; font-size: 11px; }}
  td {{ padding: 7px 10px; border-bottom: 1px solid #f0f0f0; }}
  tr:hover td {{ background: #fafafa; }}
  .badge {{ padding: 2px 7px; border-radius: 10px; font-size: 10px; font-weight: 700; }}
  .sig  {{ background: #d4edda; color: #155724; }}
  .ns   {{ background: #e9ecef; color: #666; }}
</style>
</head>
<body>

<header>
  <div>
    <h1>NFL Draft Analysis</h1>
    <small>2000 – 2024 &nbsp;·&nbsp; {total} ANOVA tests &nbsp;·&nbsp; {len(positions)} positions</small>
  </div>
</header>

<div class="tabs">
  <button class="tab-btn active" onclick="showTab('anova', this)">ANOVA Results</button>
  <button class="tab-btn"        onclick="showTab('avg',   this)">Avg Stats by Slot</button>
</div>

<!-- ANOVA PAGE -->
<div id="page-anova" class="page active">
  <div class="stats-row">
    <div class="stat-box"><div class="val">{total}</div><div class="lbl">Total tests</div></div>
    <div class="stat-box"><div class="val green">{sig_count}</div><div class="lbl">Significant (p&lt;.05)</div></div>
    <div class="stat-box"><div class="val gray">{total - sig_count}</div><div class="lbl">Not significant</div></div>
    <div class="stat-box"><div class="val">{round(sig_count/total*100,1)}%</div><div class="lbl">Sig. rate</div></div>
  </div>

  <div class="toolbar">
    <label>Position</label>
    <select id="apos" onchange="renderAnova()">
      <option value="">All</option>
      {''.join(f'<option>{p}</option>' for p in positions)}
    </select>
    <label>Show</label>
    <select id="asig" onchange="renderAnova()">
      <option value="">All</option>
      <option value="YES">Significant only</option>
      <option value="NO">Not significant only</option>
    </select>
  </div>

  <div class="card">
    <div class="chart-wrap" id="anova-wrap" style="height:480px">
      <canvas id="anova-chart"></canvas>
    </div>
  </div>

  <div class="card">
    <table><thead><tr><th>Position</th><th>Stat</th><th>F-stat</th><th>p-value</th><th>Result</th></tr></thead>
    <tbody id="anova-table"></tbody></table>
  </div>
</div>

<!-- AVG STATS PAGE -->
<div id="page-avg" class="page">
  <div class="toolbar">
    <label>Position</label>
    <select id="avg-pos" onchange="onPosChange()"></select>
    <label>Stat</label>
    <select id="avg-stat" onchange="renderAvg()"></select>
    <label>Metric</label>
    <select id="avg-metric" onchange="renderAvg()">
      <option value="mean">Mean</option>
      <option value="median">Median</option>
      <option value="std">Std dev</option>
    </select>
  </div>

  <div class="stats-row" id="avg-cards"></div>

  <div class="card">
    <div class="chart-wrap" style="height:320px">
      <canvas id="avg-chart"></canvas>
    </div>
  </div>
</div>

<script>
const ANOVA = {anova_json};
const AVG   = {avg_json};

let aC = null, avgC = null;

function showTab(name, btn) {{
  document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  btn.classList.add('active');
  document.getElementById('page-' + name).classList.add('active');
}}

//ANOVA
function renderAnova() {{
  const pos = document.getElementById('apos').value;
  const sig = document.getElementById('asig').value;
  let data = ANOVA.filter(r => (!pos || r.position === pos) && (!sig || r.significant === sig));
  data.sort((a, b) => b.f_stat - a.f_stat);

  const labels = data.map(r => r.position + ' · ' + r.stat.replace(/_/g, ' '));
  const vals   = data.map(r => r.f_stat);
  const colors = data.map(r => r.significant === 'YES' ? '#2d7a2d' : '#adb5bd');

  const h = Math.max(400, data.length * 22 + 60);
  document.getElementById('anova-wrap').style.height = h + 'px';

  if (aC) aC.destroy();
  aC = new Chart(document.getElementById('anova-chart'), {{
    type: 'bar',
    data: {{ labels, datasets: [{{ data: vals, backgroundColor: colors, borderRadius: 3, barThickness: 12 }}] }},
    options: {{
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {{ legend: {{ display: false }}, tooltip: {{ callbacks: {{ label: ctx => {{
        const r = data[ctx.dataIndex];
        return 'F=' + r.f_stat.toFixed(3) + '  p=' + (r.p_value === 0 ? '<0.0001' : r.p_value);
      }}}}}}  }},
      scales: {{
        x: {{ grid: {{ color: '#f0f0f0' }}, ticks: {{ color: '#888', font: {{ size: 10 }} }} }},
        y: {{ ticks: {{ color: '#444', font: {{ size: 10 }}, crossAlign: 'far' }} }}
      }}
    }}
  }});

  document.getElementById('anova-table').innerHTML = data.map(r => `
    <tr>
      <td><b>${{r.position}}</b></td>
      <td style="color:#555">${{r.stat.replace(/_/g,' ')}}</td>
      <td>${{r.f_stat.toFixed(3)}}</td>
      <td>${{r.p_value === 0 ? '<0.0001' : r.p_value}}</td>
      <td><span class="badge ${{r.significant==='YES'?'sig':'ns'}}">${{r.significant==='YES'?'p<.05':'n.s.'}}</span></td>
    </tr>`).join('');
}}

// ── AVG STATS ──────────────────────────────────────────────────────────────────
function buildPosSelect() {{
  const sel = document.getElementById('avg-pos');
  sel.innerHTML = Object.keys(AVG).sort().map(p => `<option>${{p}}</option>`).join('');
  onPosChange();
}}

function onPosChange() {{
  const pos   = document.getElementById('avg-pos').value;
  const stats = AVG[pos]?.stats || [];
  document.getElementById('avg-stat').innerHTML = stats.map(s =>
    `<option value="${{s}}">${{s.replace(/_/g,' ')}}</option>`).join('');
  renderAvg();
}}

function renderAvg() {{
  const pos    = document.getElementById('avg-pos').value;
  const stat   = document.getElementById('avg-stat').value;
  const metric = document.getElementById('avg-metric').value;
  const info   = AVG[pos];
  if (!info) return;

  const col    = stat + '_' + metric;
  const rows   = info.rows;
  const labels = rows.map(r => r.slot);
  const vals   = rows.map(r => r[col] ?? 0);
  const ns     = rows.map(r => r.n);
  const maxI   = vals.indexOf(Math.max(...vals));
  const total  = ns.reduce((a, b) => a + b, 0);

  document.getElementById('avg-cards').innerHTML = `
    <div class="stat-box"><div class="val">${{rows.length}}</div><div class="lbl">Draft slots</div></div>
    <div class="stat-box"><div class="val">${{total}}</div><div class="lbl">Total players</div></div>
    <div class="stat-box"><div class="val green">${{labels[maxI]}}</div><div class="lbl">Best slot</div></div>
    <div class="stat-box"><div class="val green">${{vals[maxI].toFixed(1)}}</div><div class="lbl">Best value</div></div>
  `;

  if (avgC) avgC.destroy();
  avgC = new Chart(document.getElementById('avg-chart'), {{
    type: 'bar',
    data: {{ labels, datasets: [{{
      data: vals,
      backgroundColor: vals.map((_, i) => i === maxI ? '#1a6b3c' : '#93c4a8'),
      borderRadius: 4,
      label: stat.replace(/_/g,' ') + ' (' + metric + ')'
    }}] }},
    options: {{
      responsive: true, maintainAspectRatio: false,
      plugins: {{ legend: {{ display: false }}, tooltip: {{ callbacks: {{ label: ctx =>
        ctx.raw.toFixed(1) + '  (n=' + ns[ctx.dataIndex] + ')'
      }}}}  }},
      scales: {{
        x: {{ grid: {{ display: false }}, ticks: {{ color: '#666', font: {{ size: 12 }} }} }},
        y: {{ grid: {{ color: '#f0f0f0' }}, ticks: {{ color: '#666', font: {{ size: 11 }} }} }}
      }}
    }}
  }});
}}

renderAnova();
buildPosSelect();
</script>
</body>
</html>"""

out = 'nfl_dash.html'
with open(out, 'w', encoding='utf-8') as f:
    f.write(html)

print(f'downloaded dash{out}')
files.download(out)