# -*- coding: utf-8 -*-
"""SQL_NFL_data_n_dash_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117fm5MagCoX98ZRRu2TlHcPbp4iX72VU
"""

import pandas as pd
import sqlite3 as sql
import openpyxl

avg_stats = ['AVG_QB','AVG_WR','AVG_TE','AVG_RB','AVG_DE','AVG_LB','AVG_OLB','AVG_ILB','AVG_CB','AVG_DB','AVG_S','AVG_FS','AVG_DT','AVG_K'] # List of average stats for each NFL position
total_stats = ['TOT_QB','TOT_WR','TOT_TE','TOT_RB','TOT_DE','TOT_LB','TOT_OLB','TOT_ILB','TOT_CB','TOT_DB','TOT_S','TOT_FS','TOT_DT','TOT_K'] # List of total stats """"""

db = sql.connect('nfl_draft_analysis.db') # Establish Database connection

xlsx = pd.ExcelFile('nfl_draft_analysis.xlsx') # Load Excel file
for sheet in avg_stats + total_stats:

    df = pd.read_excel(xlsx, sheet_name = sheet) # Creates a Data Frame from each Excel sheet
    df.to_sql(sheet, db, index=False, if_exists='replace') # Pushes each Data Frame as a table in the Database

df_master = pd.read_excel(xlsx,sheet_name = 'MASTER_all_players') # Adds the Master table with all stats and season
df_master.to_sql('master', db, index = False, if_exists='replace')

"""Everything above this sets up the DataBase connection and tables"""

#### Things to do using SQL
# take average position stats (the important ones)
# take average career stats of each player (the ones that are most important to that position)
# compare the player stats to the average
# for stats that arent important to their position, N/A

"""Offensive positions"""

# QB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL COMPLETIONS
                    t.completions,

                    -- TOTAL ATTEMPTS
                    t.attempts,

                    -- TOTAL PASSING YARDS
                    t.passing_yards,

                    -- TOTAL PASSING TDS
                    t.passing_tds,

                    -- TOTAL PASSING INTERCEPTIONS
                    t.passing_interceptions

            FROM TOT_QB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_QB = pd.read_sql(query, db)
df_QB.head()

# WR
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL RECEPTIONS
                    t.receptions,

                    -- TOTAL TARGETS
                    t.targets,

                    -- TOTAL RECEIVING YARDS
                    t.receiving_yards,

                    -- TOTAL RECEIVING TDS
                    t.receiving_tds,

                    -- TOTAL RECEIVING AIR YARDS
                    t.receiving_air_yards

            FROM TOT_WR t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_WR = pd.read_sql(query, db)
df_WR.head()

# RB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL CARRIES
                    t.carries,

                    -- TOTAL RUSHING YARDS
                    t.rushing_yards,

                    -- TOTAL RUSHING TDS
                    t.rushing_tds,

                    -- TOTAL RECEPTIONS
                    t.receptions,

                    -- TOTAL TARGETS
                    t.targets

            FROM TOT_RB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_RB = pd.read_sql(query, db)
df_RB.head()

# TE
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL RECEPTIONS
                    t.receptions,

                    -- TOTAL TARGETS
                    t.targets,

                    -- TOTAL RECEIVING YARDS
                    t.receiving_yards,

                    -- TOTAL RECEIVING TDS
                    t.receiving_tds,

                    -- TOTAL RECEIVING AIR YARDS
                    t.receiving_air_yards

            FROM TOT_TE t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_TE = pd.read_sql(query, db)
df_TE.head()

# OLB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_OLB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_OLB = pd.read_sql(query, db)
df_OLB.head()

# K
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL FIELD GOALS MADE
                    t.fg_made,

                    -- TOTAL FIELD GOAL ATTEMPTS
                    t.fg_att,

                    -- TOTAL FIELD GOALS MISSED
                    t.fg_missed,

                    -- LONGEST FIELD GOAL
                    t.fg_long,

                    -- TOTAL PAT MADE
                    t.pat_made

            FROM TOT_K t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_K = pd.read_sql(query, db)
df_K.head()

"""Defensive positions"""

# FS
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL QB HITS
                    t.def_qb_hits

            FROM TOT_FS t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_FS = pd.read_sql(query, db)
df_FS.head()

# DB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_DB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_DB = pd.read_sql(query,db)
df_DB.head()

# CB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss

            FROM TOT_CB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
            """

df_CB = pd.read_sql(query,db)
df_CB.head()

# S
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL QB HITS
                    t.def_qb_hits

            FROM TOT_S t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_S = pd.read_sql(query,db)
df_S.head()

# DT
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced

            FROM TOT_DT t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DT = pd.read_sql(query,db)
df_DT.head()

# DE
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL FUMBLES FORCED
                    t.def_fumbles_forced

            FROM TOT_DE t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

            """

df_DE = pd.read_sql(query,db)
df_DE.head()

# ILB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_ILB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full

        """

df_ILB = pd.read_sql(query,db)
df_ILB.head()

# LB
query = """ SELECT t.player_name_full,
                    t.college,
                    t.draft_slot,
                    t.round,
                    t.pick,

                    m.season,

                    -- TOTAL TACKLES
                    t.def_tackles_solo,

                    -- TOTAL SACKS
                    t.def_sacks,

                    -- TOTAL QB HITS
                    t.def_qb_hits,

                    -- TOTAL INTERCEPTIONS
                    t.def_interceptions,

                    -- TOTAL TACKLES FOR LOSS
                    t.def_tackles_for_loss,

                    -- TOTAL PASSES DEFENDED
                    t.def_pass_defended

            FROM TOT_LB t
            JOIN master m ON m.player_id = t.player_id

            GROUP BY t.player_name_full
        """

df_LB = pd.read_sql(query,db)
df_LB.head()

"""Get the count"""

# Count for number of players of a specific school that perform above average with respect to their draft position and position on the field

import pandas as pd

# dictionary of player dataframes
player_dfs = {
    "QB": df_QB,
    "RB": df_RB,
    "WR": df_WR,
    "TE": df_TE,
    "OLB": df_OLB,
    "K": df_K,
    "FS": df_FS,
    "DB": df_DB,
    "CB": df_CB,
    "S": df_S,
    "DT": df_DT,
    "DE": df_DE,
    "ILB": df_ILB,
    "LB": df_LB
}

# significant stats for each position
stats_dict = {
    "QB": ["completions", "attempts", "passing_yards", "passing_tds", "passing_interceptions"],
    "RB": ["carries", "rushing_yards", "rushing_tds", "receptions", "targets"],
    "WR": ["receptions", "targets", "receiving_yards", "receiving_tds", "receiving_air_yards"],
    "TE": ["receptions", "targets", "receiving_yards", "receiving_tds", "receiving_air_yards"],
    "OLB": ["def_tackles_solo", "def_sacks", "def_qb_hits", "def_interceptions", "def_tackles_for_loss"],
    "K": ["fg_made", "fg_att", "fg_missed", "fg_long", "pat_made"],
    "FS": ["def_tackles_solo", "def_interceptions", "def_pass_defended", "def_tackles_for_loss", "def_qb_hits"],
    "DB": ["def_tackles_solo", "def_interceptions", "def_pass_defended", "def_sacks", "def_tackles_for_loss"],
    "CB": ["def_tackles_solo", "def_interceptions", "def_pass_defended", "def_sacks", "def_tackles_for_loss"],
    "S": ["def_tackles_solo", "def_interceptions", "def_pass_defended", "def_tackles_for_loss", "def_qb_hits"],
    "DT": ["def_tackles_solo", "def_sacks", "def_qb_hits", "def_tackles_for_loss", "def_fumbles_forced"],
    "DE": ["def_tackles_solo", "def_sacks", "def_qb_hits", "def_tackles_for_loss", "def_fumbles_forced"],
    "ILB": ["def_tackles_solo", "def_sacks", "def_qb_hits", "def_interceptions", "def_tackles_for_loss", "def_pass_defended"],
    "LB": ["def_tackles_solo", "def_sacks", "def_qb_hits", "def_interceptions", "def_tackles_for_loss", "def_pass_defended"]
}

# function to compare player statistics by season to season averages
def compare_players_to_season_avg(player_df, stats, position_name):
    df = player_df.copy()

    season_avg = df.groupby("season")[stats].mean().reset_index()
    season_avg.columns = ["season"] + [stat + "_season_avg" for stat in stats]

    df = pd.merge(df, season_avg, on="season", how="left")

    flag_cols = []

    # compare each stat to the season average
    for stat in stats:
        avg_col = stat + "_season_avg"
        flag_col = stat + "_above"

        # for fg_missed (field goals missed) the lower the better so we look for less than in this case
        if stat == "fg_missed":
            df[flag_col] = (df[stat] < df[avg_col]).astype(int)
        else:
            df[flag_col] = (df[stat] > df[avg_col]).astype(int)

        flag_cols.append(flag_col)

    # count how many stats are above season average
    df["num_above_stats"] = df[flag_cols].sum(axis=1)

    # player counts as above average if at least 3 stats are above season average
    df["above_avg_player"] = (df["num_above_stats"] >= 3).astype(int)

    df["position"] = position_name

    return df[[
        "player_name_full",
        "college",
        "season",
        "position",
        "draft_slot",
        "num_above_stats",
        "above_avg_player"
    ]]

# store results
all_results = []

for pos in player_dfs:
    result = compare_players_to_season_avg(
        player_dfs[pos],
        stats_dict[pos],
        pos
    )
    all_results.append(result)

# combine all positions
all_players = pd.concat(all_results, ignore_index=True)

# count number of above average players by school for each season
school_year_counts = (
    all_players.groupby(["season", "college"])["above_avg_player"]
    .sum()
    .reset_index()
    .rename(columns={"above_avg_player": "num_players_above_avg"})
)

# sort by season then by number of above average players descending
school_year_counts = school_year_counts.sort_values(
    ["season", "num_players_above_avg"],
    ascending=[True, False]
)

# keep top 10 schools for each season
top10_by_season = school_year_counts.groupby("season").head(10).copy()

# sort final output
top10_by_season = top10_by_season.sort_values(
    ["season", "num_players_above_avg"],
    ascending=[True, False]
)

# function to see top 10 schools for any year
def top10_for_year(year):
    return top10_by_season[top10_by_season["season"] == year]

# example
top10_for_year(2015)

# print top 10 schools for each year 2015–2025
years = range(2015, 2025)

for year in years:
    print("\nTop 10 schools for", year)
    print("----------------------------")

    result = top10_for_year(year)

    if result.empty:
        print("No data available")
    else:
        print(result)

result = top10_for_year(year)

# sum all years together and compares schools
top10_total = (
    all_players.groupby("college")["above_avg_player"]
    .sum()
    .reset_index()
    .rename(columns={"above_avg_player": "total_above_avg_players"})
    .sort_values("total_above_avg_players", ascending=False)
    .head(10)
)

top10_total

import json, webbrowser, os

# ── Aggregate ──────────────────────────────────────────────────────────────────
season_summary_data = [
    {'season': int(s), 'total_players': len(g),
     'above_avg': int(g['above_avg_player'].sum()),
     'pct': round(g['above_avg_player'].sum() / len(g) * 100, 1)}
    for s, g in all_players.groupby('season')
]

all_time_data = (
    all_players.groupby('college')['above_avg_player'].sum()
    .reset_index().rename(columns={'above_avg_player': 'total'})
    .sort_values('total', ascending=False).head(20)
    .to_dict(orient='records')
)

pos_totals_data = (
    all_players.groupby('position')['above_avg_player'].sum()
    .reset_index().rename(columns={'above_avg_player': 'total'})
    .sort_values('total', ascending=False)
    .to_dict(orient='records')
)

top10_json = {
    str(int(yr)): grp.head(10)[['college', 'num_players_above_avg']].rename(
        columns={'num_players_above_avg': 'count'}).to_dict(orient='records')
    for yr, grp in school_year_counts.groupby('season')
}

top1           = all_time_data[0]['college'] if all_time_data else '—'
total_players  = len(all_players)
total_above    = int(all_players['above_avg_player'].sum())
unique_schools = all_players['college'].nunique()
overall_rate   = round(total_above / total_players * 100, 1)

#HTML
html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>NFL College Pipeline Dashboard</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"></script>
<style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
  body{font-family:system-ui,sans-serif;background:#f8f8f8;color:#222}
  header{background:#1a1a2e;color:#fff;padding:16px 28px;display:flex;align-items:center;gap:12px;flex-wrap:wrap}
  header h1{font-size:16px;font-weight:600}
  header small{font-size:11px;opacity:.55}
  .pill{font-size:11px;background:rgba(255,255,255,.12);padding:3px 9px;border-radius:20px}
  .tabs{display:flex;background:#fff;border-bottom:1px solid #e5e5e5;padding:0 24px}
  .tb{padding:11px 18px;font-size:13px;border:none;background:none;cursor:pointer;border-bottom:2px solid transparent;color:#666;font-family:inherit}
  .tb.active{color:#1a1a2e;border-bottom-color:#1a1a2e;font-weight:600}
  .page{display:none;padding:20px 24px;max-width:1100px;margin:0 auto}
  .page.active{display:block}
  .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}
  .metric{background:#fff;border:1px solid #e5e5e5;border-radius:8px;padding:14px 18px}
  .metric .val{font-size:28px;font-weight:700}
  .metric .lbl{font-size:11px;color:#888;margin-top:2px}
  .green{color:#2d7a2d}.blue{color:#1a5ba8}.gold{color:#b8860b}
  .toolbar{display:flex;gap:12px;align-items:center;margin-bottom:16px;flex-wrap:wrap}
  .toolbar label{font-size:12px;color:#666;font-weight:500}
  .toolbar select{font-size:12px;padding:5px 9px;border:1px solid #ddd;border-radius:5px;background:#fff;font-family:inherit}
  .card{background:#fff;border:1px solid #e5e5e5;border-radius:8px;padding:16px;margin-bottom:16px}
  .card-title{font-size:12px;font-weight:600;color:#888;text-transform:uppercase;letter-spacing:.05em;margin-bottom:14px}
  .chart-wrap{position:relative;width:100%}
  .two-col{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}
  table{width:100%;border-collapse:collapse;font-size:12px}
  th{text-align:left;padding:7px 10px;background:#f4f4f4;border-bottom:1px solid #e5e5e5;font-weight:600;color:#555;font-size:11px}
  td{padding:7px 10px;border-bottom:1px solid #f0f0f0}
  tr:hover td{background:#fafafa}
  .rank{font-weight:700;color:#1a1a2e;width:28px}
  .bar-bg{background:#eee;border-radius:3px;height:8px}
  .bar-fill{background:#1a6b3c;border-radius:3px;height:8px}
  @media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}.two-col{grid-template-columns:1fr}}
</style>
</head>
<body>
<header>
  <div><h1>NFL College Pipeline</h1><small>Which colleges produce the most above-average NFL players? · 2015–2024</small></div>
  <span class="pill">__TOTAL_PLAYERS__ player-seasons</span>
  <span class="pill">__UNIQUE_SCHOOLS__ colleges</span>
  <span class="pill">14 positions</span>
</header>
<div class="tabs">
  <button class="tb active" onclick="sw('alltime',this)">All-time rankings</button>
  <button class="tb"        onclick="sw('season',this)">By season</button>
  <button class="tb"        onclick="sw('position',this)">By position</button>
</div>

<div id="page-alltime" class="page active">
  <div class="metrics">
    <div class="metric"><div class="val">__TOTAL_PLAYERS__</div><div class="lbl">Player-seasons tracked</div></div>
    <div class="metric"><div class="val green">__TOTAL_ABOVE__</div><div class="lbl">Above-average performances</div></div>
    <div class="metric"><div class="val blue">__OVERALL_RATE__%</div><div class="lbl">Overall above-avg rate</div></div>
    <div class="metric"><div class="val gold">__TOP1__</div><div class="lbl">All-time #1 pipeline</div></div>
  </div>
  <div class="two-col">
    <div class="card">
      <div class="card-title">Top 20 schools — all-time</div>
      <div class="chart-wrap" style="height:380px"><canvas id="at-chart"></canvas></div>
    </div>
    <div class="card">
      <div class="card-title">All-time rankings</div>
      <table><thead><tr><th>#</th><th>College</th><th>Above avg</th><th>Bar</th></tr></thead>
      <tbody id="at-table"></tbody></table>
    </div>
  </div>
  <div class="card">
    <div class="card-title">Above-average players per season</div>
    <div class="chart-wrap" style="height:220px"><canvas id="trend-chart"></canvas></div>
  </div>
</div>

<div id="page-season" class="page">
  <div class="toolbar">
    <label>Season</label>
    <select id="season-sel" onchange="renderSeason()"></select>
  </div>
  <div class="metrics" id="season-metrics"></div>
  <div class="two-col">
    <div class="card">
      <div class="card-title" id="season-title">Top 10 schools</div>
      <div class="chart-wrap" style="height:300px"><canvas id="season-chart"></canvas></div>
    </div>
    <div class="card">
      <div class="card-title">Rankings</div>
      <table><thead><tr><th>#</th><th>College</th><th>Players</th><th>Bar</th></tr></thead>
      <tbody id="season-table"></tbody></table>
    </div>
  </div>
</div>

<div id="page-position" class="page">
  <div class="metrics">
    <div class="metric"><div class="val blue" id="p1n"></div><div class="lbl" id="p1l"></div></div>
    <div class="metric"><div class="val blue" id="p2n"></div><div class="lbl" id="p2l"></div></div>
    <div class="metric"><div class="val blue" id="p3n"></div><div class="lbl" id="p3l"></div></div>
    <div class="metric"><div class="val">14</div><div class="lbl">Positions tracked</div></div>
  </div>
  <div class="two-col">
    <div class="card">
      <div class="card-title">Above-avg players by position</div>
      <div class="chart-wrap" style="height:340px"><canvas id="pos-chart"></canvas></div>
    </div>
    <div class="card">
      <div class="card-title">Position breakdown</div>
      <table><thead><tr><th>#</th><th>Position</th><th>Above avg</th><th>Bar</th></tr></thead>
      <tbody id="pos-table"></tbody></table>
    </div>
  </div>
</div>

<script>
const TOP10   = __TOP10_JS__;
const ALL_TIME = __ALL_TIME_JS__;
const SEASONS  = __SEASON_JS__;
const POS      = __POS_JS__;
let C = {};

function sw(t, btn) {
  document.querySelectorAll('.tb').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.getElementById('page-' + t).classList.add('active');
}

function bar(v, mx) {
  return '<div class="bar-bg"><div class="bar-fill" style="width:' + Math.round(v/mx*100) + '%"></div></div>';
}

function initAllTime() {
  const labels = ALL_TIME.map(r => r.college);
  const vals   = ALL_TIME.map(r => r.total);
  const mx     = vals[0];
  if (C.at) C.at.destroy();
  C.at = new Chart(document.getElementById('at-chart'), {
    type: 'bar',
    data: { labels, datasets: [{ data: vals, backgroundColor: vals.map((_, i) => i===0 ? '#1a1a2e' : i<3 ? '#1a6b3c' : '#93c4a8'), borderRadius: 4 }] },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { display: false }, ticks: { color: '#666', font: { size: 10 }, maxRotation: 40 } },
        y: { grid: { color: '#f0f0f0' }, ticks: { color: '#888', font: { size: 10 } } }
      }
    }
  });
  document.getElementById('at-table').innerHTML = ALL_TIME.map((r, i) =>
    '<tr><td class="rank">' + (i+1) + '</td><td>' + r.college + '</td><td><strong>' + r.total + '</strong></td><td>' + bar(r.total, mx) + '</td></tr>'
  ).join('');

  if (C.tr) C.tr.destroy();
  C.tr = new Chart(document.getElementById('trend-chart'), {
    type: 'bar',
    data: {
      labels: SEASONS.map(r => r.season),
      datasets: [
        { label: 'Above avg', data: SEASONS.map(r => r.above_avg), backgroundColor: '#1a6b3c', borderRadius: 3, order: 2 },
        { label: '% rate', data: SEASONS.map(r => r.pct), type: 'line', borderColor: '#1a1a2e',
          backgroundColor: 'transparent', pointRadius: 4, pointBackgroundColor: '#1a1a2e',
          yAxisID: 'y2', order: 1, tension: 0.3 }
      ]
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: true, labels: { font: { size: 11 }, boxWidth: 12 } }, tooltip: { mode: 'index' } },
      scales: {
        x: { grid: { display: false }, ticks: { color: '#666', font: { size: 11 } } },
        y: { grid: { color: '#f0f0f0' }, ticks: { color: '#888', font: { size: 10 } } },
        y2: { position: 'right', grid: { display: false }, min: 25, max: 50,
              ticks: { color: '#888', font: { size: 10 }, callback: v => v + '%' } }
      }
    }
  });
}

function buildSeasonSelect() {
  const sel = document.getElementById('season-sel');
  sel.innerHTML = Object.keys(TOP10).sort().map(y => '<option>' + y + '</option>').join('');
  sel.value = Object.keys(TOP10).sort().pop();
  renderSeason();
}

function renderSeason() {
  const yr   = document.getElementById('season-sel').value;
  const data = TOP10[yr] || [];
  const ss   = SEASONS.find(r => r.season == yr) || {};
  const mx   = data[0] ? data[0].count : 1;
  document.getElementById('season-metrics').innerHTML =
    '<div class="metric"><div class="val">' + yr + '</div><div class="lbl">Season</div></div>' +
    '<div class="metric"><div class="val green">' + (data[0] ? data[0].college : '—') + '</div><div class="lbl">Top school</div></div>' +
    '<div class="metric"><div class="val blue">' + (ss.above_avg || 0) + '</div><div class="lbl">Above-avg players</div></div>' +
    '<div class="metric"><div class="val">' + (ss.pct || 0) + '%</div><div class="lbl">Above-avg rate</div></div>';
  document.getElementById('season-title').textContent = 'Top 10 schools — ' + yr;
  if (C.s) C.s.destroy();
  C.s = new Chart(document.getElementById('season-chart'), {
    type: 'bar',
    data: { labels: data.map(r => r.college), datasets: [{ data: data.map(r => r.count), backgroundColor: data.map((_, i) => i===0 ? '#1a1a2e' : i<3 ? '#1a6b3c' : '#93c4a8'), borderRadius: 4 }] },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { display: false }, ticks: { color: '#666', font: { size: 11 }, maxRotation: 35 } },
        y: { grid: { color: '#f0f0f0' }, ticks: { color: '#888', font: { size: 10 }, stepSize: 1 } }
      }
    }
  });
  document.getElementById('season-table').innerHTML = data.map((r, i) =>
    '<tr><td class="rank">' + (i+1) + '</td><td>' + r.college + '</td><td><strong>' + r.count + '</strong></td><td>' + bar(r.count, mx) + '</td></tr>'
  ).join('');
}

function initPosition() {
  const mx = POS[0].total;
  const labels = ['Most', '2nd most', '3rd most'];
  POS.slice(0, 3).forEach((r, i) => {
    document.getElementById('p' + (i+1) + 'n').textContent = r.position;
    document.getElementById('p' + (i+1) + 'l').textContent = labels[i] + ' above-avg (' + r.total + ')';
  });
  if (C.p) C.p.destroy();
  C.p = new Chart(document.getElementById('pos-chart'), {
    type: 'bar',
    data: { labels: POS.map(r => r.position), datasets: [{ data: POS.map(r => r.total), backgroundColor: POS.map((_, i) => i<3 ? ['#1a1a2e','#1a6b3c','#2d7a2d'][i] : '#93c4a8'), borderRadius: 4 }] },
    options: {
      responsive: true, maintainAspectRatio: false,
      plugins: { legend: { display: false } },
      scales: {
        x: { grid: { display: false }, ticks: { color: '#666', font: { size: 12 } } },
        y: { grid: { color: '#f0f0f0' }, ticks: { color: '#888', font: { size: 10 } } }
      }
    }
  });
  document.getElementById('pos-table').innerHTML = POS.map((r, i) =>
    '<tr><td class="rank">' + (i+1) + '</td><td><strong>' + r.position + '</strong></td><td>' + r.total + '</td><td>' + bar(r.total, mx) + '</td></tr>'
  ).join('');
}

initAllTime();
buildSeasonSelect();
initPosition();
</script>
</body>
</html>"""

html = (html
    .replace('__TOP10_JS__',    json.dumps(top10_json))
    .replace('__ALL_TIME_JS__', json.dumps(all_time_data))
    .replace('__SEASON_JS__',   json.dumps(season_summary_data))
    .replace('__POS_JS__',      json.dumps(pos_totals_data))
    .replace('__TOTAL_PLAYERS__', f'{total_players:,}')
    .replace('__TOTAL_ABOVE__',   str(total_above))
    .replace('__OVERALL_RATE__',  str(overall_rate))
    .replace('__UNIQUE_SCHOOLS__',str(unique_schools))
    .replace('__TOP1__',          top1)
)

out = 'nfl_college_dashboard.html'
with open(out, 'w', encoding='utf-8') as f:
    f.write(html)

from google.colab import files
files.download(out)