# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o_1eFOOUpp4JixlTTsnv_9ohQqFab2A5
"""

import sys
!{sys.executable} -m pip install nflreadpy

import nflreadpy as nfl

print("DRAFT PICKS COLS")
dp = nfl.load_draft_picks().to_pandas()
print(dp.columns.tolist())
print(dp.head(2).to_string())

print("\n ROSTER COLS")
r = nfl.load_rosters(seasons=[2023]).to_pandas()
print(r.columns.tolist())
print(r.head(2).to_string())

print("\nPLAYER STATS COLS")
s = nfl.load_player_stats(seasons=[2023]).to_pandas()
print(s.columns.tolist())
print(s.head(2).to_string())

import pandas as pd
import numpy as np
from scipy import stats
import re

YEARS = list(range(2015, 2025))
MIN_PLAYERS = 5
SLOT_LABELS = {1:'R1', 2:'R2', 3:'R3', 4:'R4', 5:'R5', 6:'R6', 7:'UDFA'}
def abbreviate_name(full_name):

    if pd.isna(full_name):
        return np.nan
    parts = str(full_name).strip().split()
    if len(parts) < 2:
        return full_name
    return f"{parts[0][0]}.{parts[-1]}"

STAT_COLS_BY_POS = {
    'QB': [
        'completions', 'attempts', 'passing_yards', 'passing_tds',
        'passing_interceptions', 'sacks_suffered', 'rushing_yards',
        'rushing_tds', 'passing_epa', 'fantasy_points'
    ],
    'RB': [
        'carries', 'rushing_yards', 'rushing_tds',
        'receptions', 'targets', 'receiving_yards', 'receiving_tds',
        'rushing_epa', 'receiving_epa', 'fantasy_points'
    ],
    'WR': [
        'receptions', 'targets', 'receiving_yards', 'receiving_tds',
        'receiving_air_yards', 'receiving_yards_after_catch',
        'receiving_epa', 'wopr', 'fantasy_points'
    ],
    'TE': [
        'receptions', 'targets', 'receiving_yards', 'receiving_tds',
        'receiving_air_yards', 'receiving_yards_after_catch',
        'receiving_epa', 'fantasy_points'
    ],
    'DE': [
        'def_tackles_solo', 'def_sacks', 'def_qb_hits',
        'def_tackles_for_loss', 'def_fumbles_forced'
    ],
    'LB':  ['def_tackles_solo', 'def_sacks', 'def_qb_hits',
            'def_interceptions', 'def_tackles_for_loss', 'def_pass_defended'],
    'OLB': ['def_tackles_solo', 'def_sacks', 'def_qb_hits',
            'def_interceptions', 'def_tackles_for_loss', 'def_pass_defended'],
    'ILB': ['def_tackles_solo', 'def_sacks', 'def_qb_hits',
            'def_interceptions', 'def_tackles_for_loss', 'def_pass_defended'],
    'CB':  ['def_tackles_solo', 'def_interceptions', 'def_pass_defended',
            'def_sacks', 'def_tackles_for_loss'],
    'DB':  ['def_tackles_solo', 'def_interceptions', 'def_pass_defended',
            'def_sacks', 'def_tackles_for_loss'],
    'S':   ['def_tackles_solo', 'def_interceptions', 'def_pass_defended',
            'def_tackles_for_loss', 'def_qb_hits'],
    'FS':  ['def_tackles_solo', 'def_interceptions', 'def_pass_defended',
            'def_tackles_for_loss', 'def_qb_hits'],
    'SS':  ['def_tackles_solo', 'def_interceptions', 'def_pass_defended',
            'def_tackles_for_loss', 'def_qb_hits'],
    'DT':  ['def_tackles_solo', 'def_sacks', 'def_qb_hits',
            'def_tackles_for_loss', 'def_fumbles_forced'],
    'K':   ['fg_made', 'fg_att', 'fg_missed', 'fg_long', 'pat_made', 'pat_att'],
}

rosters = nfl.load_rosters(seasons=YEARS).to_pandas()

roster_slim = rosters[[
    'season', 'full_name', 'position', 'college', 'draft_number'
]].drop_duplicates()

roster_slim.rename(columns={
    'full_name': 'player_name_full',
    'position':  'nfl_position',
}, inplace=True)

roster_slim['name_key'] = roster_slim['player_name_full'].apply(abbreviate_name)

# Undrafted = on roster, no draft_number
udfa = (
    roster_slim[roster_slim['draft_number'].isna()]
    [['player_name_full', 'name_key', 'college']]
    .drop_duplicates('name_key')
    .copy()
)
udfa['draft_slot']       = 7
udfa['draft_slot_label'] = 'UDFA'

udfa.head()

weekly = nfl.load_player_stats(seasons=YEARS).to_pandas()
weekly = weekly[weekly['season_type'] == 'REG'].copy()

numeric_cols = [c for c in [
    'completions', 'attempts', 'passing_yards', 'passing_tds',
    'passing_interceptions', 'sacks_suffered', 'sack_yards_lost',
    'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs',
    'passing_epa', 'carries', 'rushing_yards', 'rushing_tds',
    'rushing_fumbles', 'rushing_first_downs', 'rushing_epa',
    'receptions', 'targets', 'receiving_yards', 'receiving_tds',
    'receiving_fumbles', 'receiving_air_yards', 'receiving_yards_after_catch',
    'receiving_first_downs', 'receiving_epa', 'wopr',
    'def_tackles_solo', 'def_sacks', 'def_sack_yards', 'def_qb_hits',
    'def_interceptions', 'def_interception_yards', 'def_pass_defended',
    'def_tds', 'def_tackles_for_loss', 'def_fumbles_forced',
    'fg_made', 'fg_att', 'fg_missed', 'fg_long',
    'pat_made', 'pat_att',
    'fantasy_points', 'fantasy_points_ppr'
] if c in weekly.columns]

seasonal = (
    weekly
    .groupby(['player_id', 'player_name', 'position', 'season'])[numeric_cols]
    .sum()
    .reset_index()
)

# player_name in seasonal IS the abbreviated key ("A.Rodgers")
seasonal.rename(columns={'player_name': 'name_key'}, inplace=True)

seasonal.head()

draft_picks = nfl.load_draft_picks().to_pandas()
draft_picks = draft_picks[draft_picks['season'].isin(YEARS)].copy()

draft_picks.rename(columns={
    'pfr_player_name': 'player_name_full',
    'position':        'nfl_position',
}, inplace=True)


draft_picks['name_key'] = draft_picks['player_name_full'].apply(abbreviate_name)

draft_picks['draft_slot']       = draft_picks['round'].clip(upper=6).astype(int)
draft_picks['draft_slot_label'] = draft_picks['draft_slot'].map(SLOT_LABELS)

draft_picks = draft_picks[[
    'season', 'player_name_full', 'name_key', 'nfl_position', 'college',
    'round', 'pick', 'draft_slot', 'draft_slot_label', 'team'
]].copy()

draft_picks.head()

draft_lookup = (
    draft_picks[['name_key', 'player_name_full', 'nfl_position', 'college',
                 'draft_slot', 'draft_slot_label', 'round', 'pick', 'team', 'season']]
    .rename(columns={'season': 'draft_year'})
    .sort_values('draft_year')
    .drop_duplicates('name_key', keep='first')
)

# UDFA lookup: name_keys NOT already in draft_lookup
udfa_lookup = udfa[~udfa['name_key'].isin(draft_lookup['name_key'])].copy()

# Combined lookup
all_lookup = pd.concat([
    draft_lookup[['name_key', 'player_name_full', 'college',
                  'draft_slot', 'draft_slot_label', 'round', 'pick', 'draft_year']],
    udfa_lookup[['name_key', 'player_name_full', 'college',
                 'draft_slot', 'draft_slot_label']]
], ignore_index=True).drop_duplicates('name_key', keep='first')

print(f"Combined lookup:{len(all_lookup):,}")

merged = seasonal.merge(all_lookup, on='name_key', how='left')

assigned   = merged['draft_slot'].notna().sum()
unassigned = merged['draft_slot'].isna().sum()
pct        = assigned / len(merged) * 100

print(f"Master table: {len(merged):,} rows")

print(merged['position'].value_counts().head(15).to_string())
merged[['name_key', 'player_name_full', 'position', 'season',
        'college', 'draft_slot', 'draft_slot_label']].head(10)

id_cols = [c for c in [
    'player_id', 'name_key', 'player_name_full', 'position',
    'college', 'draft_slot', 'draft_slot_label', 'round', 'pick'
] if c in merged.columns]

career_by_pos = {}

for pos, stat_cols in STAT_COLS_BY_POS.items():
    avail  = [c for c in stat_cols if c in merged.columns]
    if not avail:
        continue

    pos_df = merged[merged['position'] == pos]
    if len(pos_df) == 0:
        continue

    career = pos_df.groupby(id_cols)[avail].sum().reset_index()

    # Only keep players with an assigned draft slot
    career = career[career['draft_slot'].notna()].copy()
    career['draft_slot'] = career['draft_slot'].astype(int)

    if len(career) > 0:
        career_by_pos[pos] = career
        slot_counts = career.groupby('draft_slot').size().to_dict()
        print(f"{pos}: {len(career):,} players | slot counts: {slot_counts}")

# AOVA Calculations pt1

results = {}

for pos, career in career_by_pos.items():
    stat_cols  = [c for c in STAT_COLS_BY_POS[pos] if c in career.columns]
    slot_stats = []

    for slot, grp in career.groupby('draft_slot'):
        if len(grp) < MIN_PLAYERS:
            continue
        row = {
            'draft_slot':       int(slot),
            'draft_slot_label': SLOT_LABELS.get(int(slot), str(slot)),
            'n_players':        len(grp),
        }
        for col in stat_cols:
            row[f'{col}_mean']   = round(grp[col].mean(),   2)
            row[f'{col}_std']    = round(grp[col].std(),    2)
            row[f'{col}_median'] = round(grp[col].median(), 2)
            row[f'{col}_min']    = round(grp[col].min(),    2)
            row[f'{col}_max']    = round(grp[col].max(),    2)
        slot_stats.append(row)

    if not slot_stats:
        print(f" {pos}: not enough players per slot (need ≥{MIN_PLAYERS})")
        continue

    results[pos] = pd.DataFrame(slot_stats).sort_values('draft_slot')
    print(f"\n{'='*70}")
    print(f"  {pos} — Career Avg Stats by Draft Slot  (n ≥ {MIN_PLAYERS})")
    print(f"{'='*70}")
    print(results[pos].to_string(index=False))

#ANOVA Calculations pt2


print("ANOVA — Does draft slot predict career output?")
print("YES p < 0.05 = significant   NO = not significant")


anova_rows = []

for pos, career in career_by_pos.items():
    stat_cols = [c for c in STAT_COLS_BY_POS[pos] if c in career.columns]
    for col in stat_cols:
        groups = [
            grp[col].dropna().values
            for _, grp in career.groupby('draft_slot')
            if len(grp) >= MIN_PLAYERS
        ]
        if len(groups) < 2:
            continue
        f_stat, p_val = stats.f_oneway(*groups)
        anova_rows.append({
            'position':    pos,
            'stat':        col,
            'f_stat':      round(f_stat, 3),
            'p_value':     round(p_val,  4),
            'significant': 'YES' if p_val < 0.05 else 'NO'
        })

if anova_rows:
    anova_df = pd.DataFrame(anova_rows).sort_values(['position', 'p_value'])
    print(anova_df.to_string(index=False))
else:
    anova_df = pd.DataFrame()
    print("No ANOVA results — check career_by_pos slot counts above")

#college data

college_pipeline = (
    draft_picks[draft_picks['college'].notna()]
    .groupby('college')
    .agg(
        total_drafted  = ('player_name_full', 'count'),
        r1_picks       = ('draft_slot', lambda x: (x == 1).sum()),
        r2_picks       = ('draft_slot', lambda x: (x == 2).sum()),
        r3_picks       = ('draft_slot', lambda x: (x == 3).sum()),
        r4_picks       = ('draft_slot', lambda x: (x == 4).sum()),
        r5_picks       = ('draft_slot', lambda x: (x == 5).sum()),
        r6_picks       = ('draft_slot', lambda x: (x == 6).sum()),
        avg_draft_slot = ('draft_slot', 'mean'),
    )
    .reset_index()
    .sort_values('total_drafted', ascending=False)
)
college_pipeline['avg_draft_slot'] = college_pipeline['avg_draft_slot'].round(2)

college_pipeline.head()

#Export CSVs

def safe_export(df, fname):
    if df is not None and len(df) > 0:
        df.to_csv(fname, index=False)
        print(f"  Exported  {fname}  ({len(df):,} rows)")
    else:
        print(f"  failed and Skipped {fname} (empty)")

print("\nExporting...")
safe_export(draft_picks,      'nfl_draft_picks_2000_2024.csv')
safe_export(udfa,             'udfa_players_2000_2024.csv')
safe_export(seasonal,         'nfl_seasonal_stats_2000_2024.csv')
safe_export(merged,           'nfl_master_table.csv')
safe_export(anova_df,         'anova_draft_slot_significance.csv')
safe_export(college_pipeline, 'college_nfl_pipeline.csv')

for pos, df in results.items():
    safe_export(df, f'avg_stats_{pos}_by_draft_slot.csv')

for pos, career in career_by_pos.items():
    safe_export(career, f'career_totals_{pos}.csv')

print("\nAll done!")

#all csvs to single excel file

!pip install openpyxl --quiet

import pandas as pd
from google.colab import files

output_path = 'nfl_draft_analysis.xlsx'

with pd.ExcelWriter(output_path, engine='openpyxl') as writer:

#AVERAGES
    for pos in ['QB', 'RB', 'WR', 'TE', 'DE', 'LB', 'OLB', 'ILB',
                'CB', 'DB', 'S', 'FS', 'SS', 'DT', 'K']:
        if pos in results:
            results[pos].to_excel(writer, sheet_name=f'AVG_{pos}', index=False)

#TOTALS
    for pos, career in career_by_pos.items():
        sheet = f'TOT_{pos}'
        career.to_excel(writer, sheet_name=sheet, index=False)

#ANOVA / MASTER
    if len(anova_df) > 0:
        anova_df.to_excel(writer, sheet_name='ANOVA_significance', index=False)

    merged.to_excel(writer, sheet_name='MASTER_all_players', index=False)

    draft_picks.to_excel(writer, sheet_name='MASTER_draft_picks', index=False)

    college_pipeline.to_excel(writer, sheet_name='MASTER_college_pipeline', index=False)

    udfa.to_excel(writer, sheet_name='MASTER_udfa', index=False)

print(f"\n Saved {output_path}")

files.download(output_path)